"""add parent id to comment

Revision ID: 293bcb333d7b
Revises: 9758751f8e81
Create Date: 2018-07-08 22:48:13.622684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '293bcb333d7b'
down_revision = '9758751f8e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comment', 'comment', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'parent_id')
    # ### end Alembic commands ###
