"""add edited_count to comment

Revision ID: eec160a52402
Revises: 293bcb333d7b
Create Date: 2018-07-10 14:21:43.353248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec160a52402'
down_revision = '293bcb333d7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('edited_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'edited_count')
    # ### end Alembic commands ###
