"""add timestamp mixin

Revision ID: b4515a04744d
Revises: 9d29c4123c28
Create Date: 2018-07-03 21:23:13.347354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4515a04744d'
down_revision = '9d29c4123c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('board', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('comment', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('comment', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('likes', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('likes', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('likes', 'created')
    op.drop_column('likes', 'updated')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes', sa.Column('updated', mysql.DATETIME(), nullable=True))
    op.add_column('likes', sa.Column('created', mysql.DATETIME(), nullable=False))
    op.drop_column('likes', 'updated_at')
    op.drop_column('likes', 'created_at')
    op.alter_column('comment', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('comment', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('board', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('board', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
