"""timestamp nullable false

Revision ID: 5fa69d48f5ab
Revises: b4515a04744d
Create Date: 2018-07-03 21:24:17.060152

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fa69d48f5ab'
down_revision = 'b4515a04744d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('board', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('board', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('comment', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('comment', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('likes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('likes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('post', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('post', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('post', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('post', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('likes', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('likes', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('comment', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('comment', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('board', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('board', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###
