"""fix comment count to comments count

Revision ID: c6cdb4e5c997
Revises: 31bed7ca951f
Create Date: 2018-07-02 15:15:03.849808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6cdb4e5c997'
down_revision = '31bed7ca951f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comments_count', sa.Integer(), nullable=False))
    op.drop_column('post', 'comment_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_column('post', 'comments_count')
    # ### end Alembic commands ###
