"""add relationship with comment and comment group

Revision ID: 2c1df37a2e4e
Revises: ee58094a5a7c
Create Date: 2018-07-06 15:25:07.818407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c1df37a2e4e'
down_revision = 'ee58094a5a7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('comment_group_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'comment', 'comment_group', ['comment_group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.drop_column('comment', 'comment_group_id')
    # ### end Alembic commands ###
