"""add readcount to post

Revision ID: 2a959c929605
Revises: 8806c47f528b
Create Date: 2018-06-29 18:21:51.516261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a959c929605'
down_revision = '8806c47f528b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('readcount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'readcount')
    # ### end Alembic commands ###
