"""add comments_count field to post

Revision ID: 87dacfac1903
Revises: 31bed7ca951f
Create Date: 2018-07-02 15:29:16.208262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87dacfac1903'
down_revision = '31bed7ca951f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comments_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'comments_count')
    # ### end Alembic commands ###
