"""add comment count field to post

Revision ID: 31bed7ca951f
Revises: 7681936439fc
Create Date: 2018-07-02 14:31:06.458760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31bed7ca951f'
down_revision = '7681936439fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('comment_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'comment_count')
    # ### end Alembic commands ###
